
import DashboardSideBar from "@/components/DashboardSidebar";
import Navbar from "@/components/Navbar";
import { Toast } from "@heroui/react";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="min-h-screen flex bg-[#080c16]">
            <DashboardSideBar />
            <div className="px-6 py-10 max-w-5xl w-full">
                {children}
            </div>
        </div>
  );
}
