import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toast } from "@heroui/react";

const OutfitFont = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutfitFont.variable} h-full antialiased light`}
      suppressHydrationWarning
      data-theme="light"
    >
      <body className="min-h-full flex flex-col">
        <main>
          {children}
        </main>
        <Toast.Provider />
        
      </body>
    </html>
  );
}
